apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
      - name: kuber-container
        image: vinayyadav115/kuber:latest
        ports:
        - containerPort: 8088
